sudo: false
language: node_js

before_script:
    - npm install --global gulp bower
    - npm install
    - npm install coveralls
    - bower install
    - gulp styles --production
    - gulp scripts --production

cache:
  directories:
    - bower_components
    - node_modules

after_success:
  - cat coverage/**/lcov.info | ./node_modules/coveralls/bin/coveralls.js
